auto-commits: false

read:
  - aider.CONVENTIONS

# Run Jupytext sync as a 'lint' step after Aider makes changes
lint-cmd:
  - "md: uv run jupytext --sync"
  - "ipynb: uv run jupytext --sync"
auto-lint: true

commit-language: "US English"
editor: "vim"
analytics-disable: true
