analytics-disable: true
auto-commits: false
map-tokens: 2048

commit-language: "US English"
editor: "vim"

read:
  - CONVENTIONS.md

# Run Jupytext sync as a 'lint' step after Aider makes changes
lint-cmd:
  - "md: uv run jupytext --sync"
  - "ipynb: uv run jupytext --sync"
auto-lint: true
