# .aider.conf.yml

auto-commits: false
read:
  - aider.CONVENTIONS

# Run Jupytext sync as a 'lint' step after Aider makes changes
lint-cmd:
  - "md: uv run jupytext --sync"
  - "ipynb: uv run jupytext --sync"

# This ensures Aider only commits once the files are perfectly aligned
auto-lint: true
